# Generated by Django 4.2.3 on 2023-07-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querymodel',
            old_name='title',
            new_name='MJD',
        ),
        migrations.RemoveField(
            model_name='querymodel',
            name='description',
        ),
    ]
